config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import routers
from rest.views import AlbumViewSet, PhotoViewSet

app_name = 'config'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path('^api/album/(?P<username>.+)/$', AlbumViewSet.as_view()),
    re_path('^api/photo/(?P<username>.+)/$', PhotoViewSet.as_view()),
    path('', include('photo_studio.urls')),
]

# router = routers.DefaultRouter()
# router.register(r'album', AlbumViewSet)
# router.register(r'photo', PhotoViewSet)

# urlpatterns += router.urls

photo_studio/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from .views import index, main, album, album_new, album_edit, album_delete, photo_new, signup, download, account, photo_edit, photo_delete

app_name = 'photo_studio'

urlpatterns = [
    path('', index, name='index'),
    path('main/', main, name='main'),
    path('album/<int:album_id>/', album, name='album'),
    path('album/new/', album_new, name='album_new'),
    path('album_edit/<int:album_id>/', album_edit, name='album_edit'),
    path('album_delete/<int:album_id>/', album_delete, name='album_delete'),
    path('album/<int:album_id>/photo_new/', photo_new, name='photo_new'),
    path('album/<int:album_id>/photo_edit/<int:photo_id>', photo_edit, name='photo_edit'),
    path('album/<int:album_id>/photo_delete/<int:photo_id>/', photo_delete, name='photo_delete'),
    path('album/<int:album_id>/download/', download, name='download'),

    path('login/', auth_views.LoginView.as_view(template_name='photo_studio/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', signup, name='signup'),
    path('account/', account, name='account'),
]

photo_studio/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    username = models.CharField(primary_key=True, max_length=20, verbose_name="아이디")
    phone_number = models.CharField(max_length=15, verbose_name="전화번호")
    email = models.EmailField(max_length=50, verbose_name="이메일")
    last_login = models.DateTimeField(auto_now=True, verbose_name="최근 접속일")
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name="가입일")
    first_name = models.CharField(max_length=20, verbose_name="이름")
    last_name = models.CharField(max_length=20, verbose_name="성")
    
    is_staff = models.BooleanField(default=False, verbose_name="관리자 여부")
    is_active = models.BooleanField(default=True, verbose_name="활성화 여부")
    is_superuser = models.BooleanField(default=False, verbose_name="최고 관리자 여부")

    def __str__(self):
        return self.username
    
    class Meta:
        verbose_name = "사용자"
        verbose_name_plural = "사용자"
    
class Album(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="사용자")
    title = models.CharField(max_length=50, verbose_name="제목")
    start_date = models.DateField(verbose_name="시작일", blank=True, null=True)
    end_date = models.DateField(verbose_name="종료일", blank=True, null=True)
    description = models.CharField(max_length=100, verbose_name="설명")
    thumbnail = models.ImageField(upload_to="static/thumbnail", verbose_name="썸네일", default="", null=False)
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "앨범"
        verbose_name_plural = "앨범"
    
class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE, verbose_name="앨범")
    title = models.CharField(max_length=50, verbose_name="제목")
    description = models.CharField(max_length=100, verbose_name="설명")
    image = models.ImageField(upload_to="static/img/%Y/%m/%d", verbose_name="이미지")
    property = models.CharField(max_length=50, verbose_name="속성", default="", null=False)
    owner = models.CharField(max_length=20, verbose_name="사용자")
    
    def __str__(self):
        return self.title
    
    def album_title(self):
        return self.album.title
    
    class Meta:
        verbose_name = "사진"
        verbose_name_plural = "사진"

class Photo_templates(models.Model):
    template_url = models.ImageField(upload_to="static/img/templates", verbose_name="템플릿")
    property = models.CharField(max_length=50, verbose_name="속성", default="", null=False)

    def __str__(self):
        return self.template_url.name
    
    class Meta:
        verbose_name = "템플릿"
        verbose_name_plural = "템플릿"

photo_studio/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from .models import User, Album, Photo


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email", "phone_number", "first_name", "last_name")

class UserFormForEdit(UserChangeForm):
    class Meta:
        model = User
        fields = ("email", "phone_number", "first_name", "last_name")

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ("title", "start_date", "end_date", "description")

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ("title", "description", "image", "property")

photo_studio/views.py
from datetime import datetime
from PIL import Image, ExifTags
from django.http import Http404, HttpResponse, FileResponse, HttpResponseForbidden, HttpResponseNotFound, HttpResponseServerError
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.template import TemplateDoesNotExist
import requests

from photo_studio.forms import UserForm, UserFormForEdit, AlbumForm, PhotoForm
from .models import Album, Photo, Photo_templates

# Create your views here.

def index(request):
    try:
        return render(request, 'photo_studio/index.html')
    except TemplateDoesNotExist:
        return HttpResponseServerError('Template does not exist')
    except Exception as e:
        return HttpResponseServerError('Something went wrong: ' + str(e))

@login_required
def main(request):
    context = {}
    try:
        albums = Album.objects.filter(owner=request.user)
    except Album.DoesNotExist:
        albums = None
    
    context['albums'] = albums
    return render(request, 'photo_studio/main.html', context=context)

@login_required
def album(request, album_id):
    context = {}
    
    try:
        album_title = Album.objects.get(id=album_id, owner=request.user).title
        photos = Photo.objects.filter(album_id=album_id, album__owner=request.user)
        photo_templates = Photo_templates.objects.all()
    except Album.DoesNotExist:
        return HttpResponseNotFound()
    
    context['photo_templates'] = photo_templates
    context['album_title'] = album_title
    context['photos'] = photos
    context['album_id'] = album_id
    return render(request, 'photo_studio/album.html', context=context)

@login_required
def album_new(request):
    if request.method == "POST":
        form = AlbumForm(request.POST)
        if form.is_valid():
            album = form.save(commit=False)
            album.owner = request.user
            try:
                response = requests.get(f"http://203.252.230.243:5680/{album.title}")
                with open(f"static/img/thumbnail/{album.title}.png", "wb") as f:
                    f.write(response.content)
                album.thumbnail = f"static/img/thumbnail/{album.title}.png"
            except:
                album.thumbnail = "static/img/thumbnail/default.png"
            album.save()
            return redirect('photo_studio:main')
    else:
        form = AlbumForm()
    return render(request, 'photo_studio/album_new.html', {'form': form})

@login_required
def album_edit(request, album_id):
    context = {}
    context['album_id'] = album_id
    if request.method == "POST":
        form = AlbumForm(request.POST)
        album = Album.objects.get(id=album_id)
        if form.is_valid():
            album.title = form.cleaned_data['title']
            album.start_date = form.cleaned_data['start_date']
            album.end_date = form.cleaned_data['end_date']
            album.description = form.cleaned_data['description']
            album.thumbnail = form.cleaned_data['thumbnail']
            album.save()
            return redirect('photo_studio:main')
    else:
        try:
            album = Album.objects.get(id=album_id)
        except Album.DoesNotExist:
            raise Http404
        form = AlbumForm(instance=album)
        context['form'] = form
        context['start_date'] = str(album.start_date)
        context['end_date'] = str(album.end_date)
    return render(request, 'photo_studio/album_edit.html', context=context)

@login_required
def album_delete(request, album_id):
    try:
        album = Album.objects.get(id=album_id)
        if album.owner != request.user:
            return HttpResponseForbidden()
        album.delete()
    except Album.DoesNotExist:
        return HttpResponseNotFound()
    return redirect('photo_studio:main')

@login_required
def photo_new(request, album_id):
    context = {}
    context['album_id'] = album_id
    album = get_object_or_404(Album, id=album_id)
    context['album'] = album

    if request.method == "POST":
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.album = album
            photo.owner = request.user
            photo.save()
            return redirect('photo_studio:album', album_id=album_id)
        else:
            messages.error(request, "사진을 선택해주세요.")
    else:
        form = PhotoForm()
    context['form'] = form
    return render(request, 'photo_studio/photo_new.html', context=context)

# photo_studio/views.py
@login_required
def photo_edit(request, album_id, photo_id):
    context = {}
    context['album_id'] = album_id
    context['photo_id'] = photo_id

    try:
        photo = Photo.objects.get(id=photo_id)
    except Photo.DoesNotExist:
        raise Http404

    if request.method == "POST":
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo.title = form.cleaned_data['title']
            photo.description = form.cleaned_data['description']
            photo.image = form.cleaned_data['image']
            photo.property = form.cleaned_data['property']
            photo.save()
            return redirect('photo_studio:album', album_id=album_id)
        else:
            context['form'] = form
    else:
        form = PhotoForm(instance=photo)
        context['form'] = form
    return render(request, 'photo_studio/photo_edit.html', context=context)

@login_required
def photo_delete(request, album_id, photo_id):
    try:
        photo = Photo.objects.get(id=photo_id)
    except Photo.DoesNotExist:
        return redirect('photo_studio:album', album_id=album_id)
    if str(photo.owner) != str(request.user):
        return redirect('photo_studio:album', album_id=album_id)
    else:
        photo.delete()
    return redirect('photo_studio:album', album_id=album_id)

@login_required
def download(request, album_id):
    context = {}
    context['album_id'] = album_id
    response = None
    if request.method == "POST":
        # photo_logo = Image.open('static/img/PhotoStudio.png').resize((650, 270))
        now = datetime.now()
        photo_ids = request.POST.getlist('photo_id')
        photo_list = []
        template_id = request.POST.getlist('template_id')[0]
        template = Photo_templates.objects.get(id=template_id)
        template_property = template.property
        if template_property == '가로':
            template = Image.open(template.template_url).resize((1800, 1200))
            for photo_id in photo_ids:
                photo = Photo.objects.get(id=photo_id)
                photo = Image.open(photo.image)
                for orientation in ExifTags.TAGS.keys() : 
                    if ExifTags.TAGS[orientation]=='Orientation' : break 
                try:
                    exif=dict(photo._getexif().items())
                    if exif[orientation] == 3 : 
                        photo=photo.rotate(180, expand=True)
                    elif exif[orientation] == 6 : 
                        photo=photo.rotate(270, expand=True)
                    elif exif[orientation] == 8 : 
                        photo=photo.rotate(90, expand=True)
                except:
                    pass
                photo_list.append(photo.resize((651 , 520)))

            # 짝수번째
            x_offset = 69
            y_offset = 68
            for photo_id in range(0, len(photo_list), 2):
                template.paste(photo_list[photo_id], (x_offset, y_offset))
                y_offset += 538
            
            # 홀수번째
            x_offset = 738
            y_offset = 68
            for photo_id in range(1, len(photo_list), 2):
                template.paste(photo_list[photo_id], (x_offset, y_offset))
                y_offset += 538

            template.save(f'static/img/merge_image/{now.strftime("%Y-%m-%d_%H_%M_%S")}.png')
            img = open(f'static/img/merge_image/{now.strftime("%Y-%m-%d_%H_%M_%S")}.png', 'rb')
            
        elif template_property == '세로':
            template = Image.open(template.template_url).resize((1200, 1800))
            for photo_id in photo_ids:
                photo = Photo.objects.get(id=photo_id)
                photo = Image.open(photo.image)
                for orientation in ExifTags.TAGS.keys() : 
                    if ExifTags.TAGS[orientation]=='Orientation' : break 
                try:
                    exif=dict(photo._getexif().items())
                    if exif[orientation] == 3 : 
                        photo=photo.rotate(180, expand=True)
                    elif exif[orientation] == 6 : 
                        photo=photo.rotate(270, expand=True)
                    elif exif[orientation] == 8 : 
                        photo=photo.rotate(90, expand=True)
                except:
                    pass
                photo_list.append(photo.resize((508 , 612)))

            # 짝수번째
            x_offset = 64
            y_offset = 425
            for photo_id in range(0, len(photo_list), 2):
                template.paste(photo_list[photo_id], (x_offset, y_offset))
                y_offset += 637
            
            # 홀수번째
            x_offset = 630
            y_offset = 128
            for photo_id in range(1, len(photo_list), 2):
                template.paste(photo_list[photo_id], (x_offset, y_offset))
                y_offset += 637
            
            template.save(f'static/img/merge_image/{now.strftime("%Y-%m-%d_%H_%M_%S")}.png')
            img = open(f'static/img/merge_image/{now.strftime("%Y-%m-%d_%H_%M_%S")}.png', 'rb')
        response = FileResponse(img, content_type='image/png')
        response['Content-Disposition'] = 'attachment; filename="merge_image.png"'
        return response
    render(request, 'photo_studio/download.html', context=context)

#에러메세지 출력하는 가능하게 하기
def signup(request):

templates/photo_studio/account.html
{% extends "photo_studio/base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'photo_studio:login' %}">
        {% csrf_token %}
        {% include "photo_studio/form_errors.html" %}
        <div class="mb-3">
            <label for="last_name">성</label>
            <input type="text" class="form-control" name="last_name" id="last_name"
                   value="{{ form.last_name.value|default_if_none:'' }}" required>
        </div>
        <div class="mb-3">
            <label for="first_name">이름</label>
            <input type="text" class="form-control" name="first_name" id="first_name"
                   value="{{ form.first_name.value|default_if_none:'' }}" required>
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}" required>
        </div>
        <div class="mb-3">
            <label for="phone_number">전화번호</label>
            <input type="text" class="form-control" name="phone_number" id="phone_number"
                   value="{{ form.phone_number.value|default_if_none:'' }}" placeholder="010-1234-5678" required>
        </div>
        <button type="submit" class="btn btn-primary">수정</button>
    </form>
</div>
{% endblock content %}

templates/photo_studio/album.html
{% extends 'photo_studio/base.html' %}
{% block content %}
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">{{ album_title }}</h1>
                <button type="button" 
                        class="btn btn-outline-light btn-lg mt-4" 
                        onclick="location.href='{% url "photo_studio:photo_new" album_id=album_id %}'">
                        사진 추가
                </button>
            </div>
        </div>
    </header>
    {% if photos %}
    <form method="POST" action="{% url 'photo_studio:download' album_id=album_id %}">
        {% csrf_token %}
        <div style="margin: 0 auto;">
            <div class="justify-content-center text-center" style="margin-top:1rem; margin-bottom:1rem;">
                <input type="submit" 
                       class="btn btn-primary" 
                       value="네컷사진 다운로드" 
                       action="{% url 'photo_studio:download' album_id=album_id %}">
            </div>
        </div>
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 justify-content-center">
                {% if photo_templates %}
                    {% for template in photo_templates %}
                        <div class="col" style="padding-bottom:1rem;">
                            <div class="card" id="studio" >
                                <div class="card-header">
                                    <p>{{ template.property }}
                                        <input 
                                            class="template{{ template.id }}"
                                            type="radio"
                                            name="template_id"
                                            value="{{ template.id }}"
                                            onclick="select_limit('{{ template.property }}', '{{ template.id }}')">
                                    </p>
                                </div>
                                <div class="card-body">
                                    <img class="img-thumbnail flex" 
                                        src="{{ template.template_url.url }}"
                                        style="width:200px; height:200px;">
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5"> 
                <div class="grid gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 justify-content-center">
                    <div class="grid-sizer grid-item mb-5"></div>
                    {% for photo in photos %}
                        <div class="grid-item" style="padding-left:10px; padding-right:10px;">
                            <div id="studio" class="card text-dark bg-light mb-3" style="max-width: 18rem; margin:0 auto;">
                                <img src="{{ photo.image.url }}" alt="{{ photo.title }}" class="card-img-top">
                                <div class="card-body">
                                    <div class="text-center">
                                        <h5 class="card-title">
                                            {{ photo.title }} 
                                            <input id="{{ photo.property }}" 
                                                class="photo{{ photo.id }} select_photo" 
                                                type="checkbox" 
                                                name="photo_id" 
                                                value="{{ photo.id }}"
                                                disabled>
                                        </h5>
                                        <p class="card-text">{{ photo.description }}</p>
                                        <div class="dropdown">
                                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                옵션
                                            </button>
                                            <ul class="dropdown-menu">
                                                <li><a class="dropdown-item" href="{% url 'photo_studio:photo_edit' photo_id=photo.id album_id=album_id %}">수정</a></li>
                                                <li><a class="dropdown-item" href="{% url 'photo_studio:photo_delete' photo_id=photo.id album_id=album_id %}">삭제</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </form>
    {% else %}
        <h1 style="text-align:center; padding:10px;">사진을 추가해주세요.</h1>
    {% endif %}
<script>
    var check_vartical = document.querySelectorAll('#세로');
    var check_horizontal = document.querySelectorAll('#가로');

    function select_limit(property, id){
        if(document.querySelector(`.template${id}`).checked == true){
            if(property == '가로'){
                for(var i=0; i<check_vartical.length; i++){
                    check_vartical[i].disabled = true;
                }
                for(var i=0; i<check_horizontal.length; i++){
                    check_horizontal[i].disabled = false;                 
                }
            }
            else if(property == '세로'){
                for(var i=0; i<check_horizontal.length; i++){
                    check_horizontal[i].disabled = true;
                }
                for(var i=0; i<check_vartical.length; i++){
                    check_vartical[i].disabled = false;
                }
            }
        }
    }
</script>
{% endblock content %}

templates/photo_studio/album_edit.html
{% extends 'photo_studio/base.html' %}
{% block content %}
    <div class="container my-3 py-3" style="text-align:center;">
        <h1><b>앨범 수정</b></h1>
    </div>
    <div class="container my-3" style="display: flex; justify-content: center;">
        <form method="post" action="{% url 'photo_studio:album_edit' album_id=album_id %}">
            {% csrf_token %}
            {% include "photo_studio/form_errors.html" %}
            <div class="col-12 mb-3">
                <label for="title">제목</label>
                <input type="text" class="form-control" name="title" id="title"
                    value="{{ form.title.value|default_if_none:'' }}" required>
            </div>
            <div class="col-12 mb-3">
                <label for="start_date">시작날짜</label>
                <input type="date" class="form-control" name="start_date" id="start_date"
                    value="{{ start_date|default_if_none:'' }}" required>
            </div>
            <div class="col-12 mb-3">
                <label for="end_date">종료날짜</label>
                <input type="date" class="form-control" name="end_date" id="end_date"
                    value="{{ end_date|default_if_none:'' }}" required>
            </div>
            <div class="col-12 mb-3">
                <label for="description">설명</label>
                <textarea class="form-control" name="description" id="description" style="font-size:1rem; height:15rem">{{ form.description.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary col-12">수정</button>
        </form>
    </div>
{% endblock content %}

templates/photo_studio/footer.html
<footer class="py-5 mt-auto" id="footer" style="background-color:#A27B5C; position:relative;">
    <div class="container"><p class="m-0 text-center text-white"><b>Copyright &copy; Taeyoung Park</b></p></div>
</footer>

templates/photo_studio/login.html
{% extends "photo_studio/base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'photo_studio:login' %}">
        {% csrf_token %}
        {% include "photo_studio/form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}" required>
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}" required>
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock content %}

templates/photo_studio/main.html
{% extends 'photo_studio/base.html' %}
{% block content %}
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">앨범 리스트</h1>
                <p class="lead fw-normal text-white-50 mb-0">앨범을 클릭해주세요</p>
                <button type="button" class="btn btn-outline-light btn-lg mt-4" onclick="location.href='{% url "photo_studio:album_new" %}'">앨범 추가</button>
            </div>
        </div>
    </header>
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5"> 
            <div class="grid gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 justify-content-center">
                {% if albums %}
                    <div class="grid-sizer grid-item mb-5"></div>
                    {% for album in albums %}
                        <div class="grid-item"style="padding-left:10px; padding-right:10px;">
                            <div id="studio" class="card text-dark bg-light mb-3">
                                <div onclick="location.href='{% url "photo_studio:album" album_id=album.id %}'">
                                    <img {% if album.thumbnail %} src="{{ album.thumbnail.url }}"{% endif %}alt="AI 이미지 생성 예정" class="card-img-top">
                                    <div class="card-body">
                                        <div class="text-center">
                                            <h2 class="card-title">{{ album.title }}</h2>
                                            <p class="card-text">{{ album.description }}</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body dropdown text-center">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        옵션
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="{% url 'photo_studio:album_edit' album_id=album.id %}">수정</a></li>
                                        <li><a class="dropdown-item" href="{% url 'photo_studio:album_delete' album_id=album.id %}">삭제</a></li>
                                    </ul>
                                </div>                                
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                <h1 style="text-align:center; padding:10px;">앨범을 추가해주세요.</h1>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock content %}

templates/photo_studio/navbar.html
<nav class="navbar navbar-expand-lg border-bottom" style="background-color:#2C3639; font-size:1.2rem;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'photo_studio:index' %}" style="font-size:1.6rem;"><b>PhotoStudio</b></a>
        <div class="collapse navbar-collapse item2" id="navbarSupportedContent" style="float:left; z-index:1;">
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'photo_studio:main' %}">Main</a>
                </li>
            </ul>
            {% if request.path != '/' %}
            <div class="search_text" style="font-size:1rem; position:relative; width:300px; margin:0 auto;">
                {% if request.path != '/login/' and 'new' not in request.path and request.path != '/account/' %}
                    <input class="form-control me-2" type="text" id="search_photo" placeholder="Search" aria-label="Search" oninput="search()">
                {% endif %}
                <ul class="list-group" style="width:100%; position:absolute;"></ul>
            </div>
            {% endif %}
        </div>
        <div class="item1">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="flex-direction: row; float: right; font-size:80%;">
                {% if user.is_authenticated %}
                    <li class="nav-item" id="account-settings">
                        <a class="nav-link" href="{% url 'photo_studio:account' %}" >{{ user.username }}</a>
                    </li>
                    <li class="nav-item" id="account-settings">
                        <a class="nav-link" href="{% url 'photo_studio:logout' %}" onclick='alert("로그아웃 되었습니다")'>로그아웃</a>
                    </li>
                {% else %}
                    <li class="nav-item" id="account-settings">
                        <a class="nav-link" href="{% url 'photo_studio:login' %}">로그인</a>
                    </li>
                {% endif %}
                <li>
                    {% if not user.is_authenticated %}
                        <a class="nav-link" id="account-settings" href="{% url 'photo_studio:signup' %}">회원가입</a>
                    {% endif %}
                </li>
                <li>
                    <button class="navbar-toggler" type="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent"
                            aria-expanded="false"
                            aria-label="Toggle navigation"
                            onclick="">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                </li>
            </ul>
        </div>
    </div>
</nav>